// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/flutter_kiwi_ffi.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterKiwiFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterKiwiFfiBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterKiwiFfiBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Initializes an analyzer instance.
  /// model_path can be null/empty for embedded/default model paths.
  ffi.Pointer<flutter_kiwi_ffi_handle_t> flutter_kiwi_ffi_init(
    ffi.Pointer<ffi.Char> model_path,
    int num_threads,
    int build_options,
    int match_options,
  ) {
    return _flutter_kiwi_ffi_init(
      model_path,
      num_threads,
      build_options,
      match_options,
    );
  }

  late final _flutter_kiwi_ffi_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<flutter_kiwi_ffi_handle_t> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutter_kiwi_ffi_init');
  late final _flutter_kiwi_ffi_init = _flutter_kiwi_ffi_initPtr
      .asFunction<
        ffi.Pointer<flutter_kiwi_ffi_handle_t> Function(
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
        )
      >();

  /// Releases all resources for an analyzer instance.
  int flutter_kiwi_ffi_close(ffi.Pointer<flutter_kiwi_ffi_handle_t> handle) {
    return _flutter_kiwi_ffi_close(handle);
  }

  late final _flutter_kiwi_ffi_closePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<flutter_kiwi_ffi_handle_t>)
        >
      >('flutter_kiwi_ffi_close');
  late final _flutter_kiwi_ffi_close = _flutter_kiwi_ffi_closePtr
      .asFunction<int Function(ffi.Pointer<flutter_kiwi_ffi_handle_t>)>();

  /// Returns analysis output as a JSON string allocated by this library.
  /// Call flutter_kiwi_ffi_free_string to free the returned value.
  ffi.Pointer<ffi.Char> flutter_kiwi_ffi_analyze_json(
    ffi.Pointer<flutter_kiwi_ffi_handle_t> handle,
    ffi.Pointer<ffi.Char> text,
    int top_n,
    int match_options,
  ) {
    return _flutter_kiwi_ffi_analyze_json(handle, text, top_n, match_options);
  }

  late final _flutter_kiwi_ffi_analyze_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<flutter_kiwi_ffi_handle_t>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutter_kiwi_ffi_analyze_json');
  late final _flutter_kiwi_ffi_analyze_json = _flutter_kiwi_ffi_analyze_jsonPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<flutter_kiwi_ffi_handle_t>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
        )
      >();

  /// Runs analysis for multiple sentences and returns a JSON object:
  /// {"results":[{"candidates":[...]}, ...]}.
  /// Call flutter_kiwi_ffi_free_string to free the returned value.
  ffi.Pointer<ffi.Char> flutter_kiwi_ffi_analyze_json_batch(
    ffi.Pointer<flutter_kiwi_ffi_handle_t> handle,
    ffi.Pointer<ffi.Pointer<ffi.Char>> texts,
    int text_count,
    int top_n,
    int match_options,
  ) {
    return _flutter_kiwi_ffi_analyze_json_batch(
      handle,
      texts,
      text_count,
      top_n,
      match_options,
    );
  }

  late final _flutter_kiwi_ffi_analyze_json_batchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<flutter_kiwi_ffi_handle_t>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('flutter_kiwi_ffi_analyze_json_batch');
  late final _flutter_kiwi_ffi_analyze_json_batch =
      _flutter_kiwi_ffi_analyze_json_batchPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<flutter_kiwi_ffi_handle_t>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              int,
              int,
              int,
            )
          >();

  /// Runs analysis and returns the token count of the first candidate.
  /// Returns 0 on success and writes to out_token_count.
  int flutter_kiwi_ffi_analyze_token_count(
    ffi.Pointer<flutter_kiwi_ffi_handle_t> handle,
    ffi.Pointer<ffi.Char> text,
    int top_n,
    int match_options,
    ffi.Pointer<ffi.Int32> out_token_count,
  ) {
    return _flutter_kiwi_ffi_analyze_token_count(
      handle,
      text,
      top_n,
      match_options,
      out_token_count,
    );
  }

  late final _flutter_kiwi_ffi_analyze_token_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<flutter_kiwi_ffi_handle_t>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('flutter_kiwi_ffi_analyze_token_count');
  late final _flutter_kiwi_ffi_analyze_token_count =
      _flutter_kiwi_ffi_analyze_token_countPtr
          .asFunction<
            int Function(
              ffi.Pointer<flutter_kiwi_ffi_handle_t>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
              ffi.Pointer<ffi.Int32>,
            )
          >();

  /// Runs analysis for multiple sentences and returns first-candidate token
  /// counts for each sentence in order.
  /// Returns 0 on success and writes to out_token_counts[text_count].
  int flutter_kiwi_ffi_analyze_token_count_batch(
    ffi.Pointer<flutter_kiwi_ffi_handle_t> handle,
    ffi.Pointer<ffi.Pointer<ffi.Char>> texts,
    int text_count,
    int top_n,
    int match_options,
    ffi.Pointer<ffi.Int32> out_token_counts,
  ) {
    return _flutter_kiwi_ffi_analyze_token_count_batch(
      handle,
      texts,
      text_count,
      top_n,
      match_options,
      out_token_counts,
    );
  }

  late final _flutter_kiwi_ffi_analyze_token_count_batchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<flutter_kiwi_ffi_handle_t>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('flutter_kiwi_ffi_analyze_token_count_batch');
  late final _flutter_kiwi_ffi_analyze_token_count_batch =
      _flutter_kiwi_ffi_analyze_token_count_batchPtr
          .asFunction<
            int Function(
              ffi.Pointer<flutter_kiwi_ffi_handle_t>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              int,
              int,
              int,
              ffi.Pointer<ffi.Int32>,
            )
          >();

  /// Runs repeated analysis for the same batch and returns the summed
  /// first-candidate token counts across all runs.
  /// Returns 0 on success and writes to out_total_tokens.
  int flutter_kiwi_ffi_analyze_token_count_batch_runs(
    ffi.Pointer<flutter_kiwi_ffi_handle_t> handle,
    ffi.Pointer<ffi.Pointer<ffi.Char>> texts,
    int text_count,
    int runs,
    int top_n,
    int match_options,
    ffi.Pointer<ffi.Int64> out_total_tokens,
  ) {
    return _flutter_kiwi_ffi_analyze_token_count_batch_runs(
      handle,
      texts,
      text_count,
      runs,
      top_n,
      match_options,
      out_total_tokens,
    );
  }

  late final _flutter_kiwi_ffi_analyze_token_count_batch_runsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<flutter_kiwi_ffi_handle_t>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('flutter_kiwi_ffi_analyze_token_count_batch_runs');
  late final _flutter_kiwi_ffi_analyze_token_count_batch_runs =
      _flutter_kiwi_ffi_analyze_token_count_batch_runsPtr
          .asFunction<
            int Function(
              ffi.Pointer<flutter_kiwi_ffi_handle_t>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              int,
              int,
              int,
              int,
              ffi.Pointer<ffi.Int64>,
            )
          >();

  /// Adds a user word to the in-memory dictionary.
  int flutter_kiwi_ffi_add_user_word(
    ffi.Pointer<flutter_kiwi_ffi_handle_t> handle,
    ffi.Pointer<ffi.Char> word,
    ffi.Pointer<ffi.Char> tag,
    double score,
  ) {
    return _flutter_kiwi_ffi_add_user_word(handle, word, tag, score);
  }

  late final _flutter_kiwi_ffi_add_user_wordPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<flutter_kiwi_ffi_handle_t>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Float,
          )
        >
      >('flutter_kiwi_ffi_add_user_word');
  late final _flutter_kiwi_ffi_add_user_word =
      _flutter_kiwi_ffi_add_user_wordPtr
          .asFunction<
            int Function(
              ffi.Pointer<flutter_kiwi_ffi_handle_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              double,
            )
          >();

  /// Frees heap strings returned by this library.
  void flutter_kiwi_ffi_free_string(ffi.Pointer<ffi.Char> value) {
    return _flutter_kiwi_ffi_free_string(value);
  }

  late final _flutter_kiwi_ffi_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'flutter_kiwi_ffi_free_string',
      );
  late final _flutter_kiwi_ffi_free_string = _flutter_kiwi_ffi_free_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Returns last error for current thread. Returns null if there is no error.
  ffi.Pointer<ffi.Char> flutter_kiwi_ffi_last_error() {
    return _flutter_kiwi_ffi_last_error();
  }

  late final _flutter_kiwi_ffi_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'flutter_kiwi_ffi_last_error',
      );
  late final _flutter_kiwi_ffi_last_error = _flutter_kiwi_ffi_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Returns wrapper version.
  ffi.Pointer<ffi.Char> flutter_kiwi_ffi_version() {
    return _flutter_kiwi_ffi_version();
  }

  late final _flutter_kiwi_ffi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'flutter_kiwi_ffi_version',
      );
  late final _flutter_kiwi_ffi_version = _flutter_kiwi_ffi_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class flutter_kiwi_ffi_handle extends ffi.Opaque {}

typedef flutter_kiwi_ffi_handle_t = flutter_kiwi_ffi_handle;
